services:
  db:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: bearodactyl
      MONGO_INITDB_ROOT_PASSWORD: ReggieMyLove<3<3
      MONGO_INITDB_DATABASE: bearodata
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok", "--quiet"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 40s

  backend:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      MONGODB_URI: mongodb://bearodactyl:ReggieMyLove<3<3@db:27017/bearodata?authSource=admin
      ROCKET_ADDRESS: 0.0.0.0
      ROCKET_PORT: 2379
    ports:
      - "2379:2379"

volumes:
  db_data:
